version: '3'

services: 
  server:
    image: 'prom/prometheus:v1.5.2'
    ports: 
      - 9090:9090
    volumes: 
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./config/prometheus.rules:/etc/prometheus/prometheus.rules
    entrypoint:
      - /bin/prometheus
      - -config.file=/etc/prometheus/prometheus.yml
      - -storage.local.path=/prometheus
      - -web.console.libraries=/etc/prometheus/console_libraries
      - -web.console.templates=/etc/prometheus/consoles
      - -alertmanager.url=http://alertmanager:9093
    depends_on:
      - alertmanager
  blackbox:
    image: 'prom/blackbox-exporter'
    ports:
      - 9115:9115
    volumes:
      - ./config/blackbox.yml:/etc/blackbox_exporter/blackbox.yml
    entrypoint:
      - bin/blackbox_exporter
      - -config.file=/etc/blackbox_exporter/blackbox.yml
  alertmanager:
    image: 'prom/alertmanager'
    ports:
      - 9093:9093
    volumes:
      - ./config/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    entrypoint:
      - /bin/alertmanager
      - -config.file=/etc/alertmanager/alertmanager.yml
      - -storage.path=/alertmanager
  grafana:
    image: grafana/grafana
    depends_on:
      - server
    ports:
      - 3000:3000
    volumes:
      - ./data/grafana/:/var/lib/grafana
    env_file:
      - ./config/grafana.env
          