global:
  # slack_api_url: 'https://hooks.slack.com/services/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'
  
route:
  receiver: 'team-apm-slack'
  group_by: ['alertname','cluster']

  # routes:
  # - match_re:
  #     service: ^(foo1|foo2|baz)$
  #   receiver: team-apm-slack
  #   routes:
  #   - match:
  #       severity: critical
  #     receiver: team-apm-slack
    
# inhibit_rules:
# - source_match:
#     severity: 'critical'
#   target_match:
#     severity: 'warning'
#   # Apply inhibition if the alertname is the same.
#   equal: ['alertname']

receivers:
- name: 'team-apm-slack'
  slack_configs:
  - api_url: 'https://hooks.slack.com/services/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'
    channel: '#kingathon'